### ISSUE TITLE
Info Tree

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO#129]
Enlever infos inutiles
Hiérarchie patientCode => visitModality => visitName (statusForm, statusUpload, reviewStatus, stateQuallityControl)

**Comment by salimkanoun** [comment]
@EmilieOLIVIE j'ai cleané les info du tree (enlevé ce qui doit pas etre transmis au front) et j'ai passé les clés en camelCase, a verif que ca te casse pas tout coté front.
