### ISSUE TITLE
getVisitPatient

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO#136]
Manque info sur reviewStatus (dépend de la study courante) + nb of series + acquisitionDate (faire evoluter acquition date vers visit date et voir utilité d'afficher le nombes de series dans la table patient)

**Comment by salimkanoun** [comment]
@EmilieOLIVIE 
j'ai changé la route pour l'api de get visit, pour avoir la study courrant et envoyer le review status de cette visite dans la study courrante
studies/{studyName}/visits/{id}

Nb series on peut enlever de la table
et l'acquisition date devient visitDate

Dans la creation de visit par ailleur j'ai ajouté un check sur le format de la data, il doit etre au format SQL YYYY-MM-DD
