### ISSUE TITLE
Tester deleteVisit (visitStatusDone)

### ISSUE THREAD

**Issue by EmilieOLIVIE** [salimkanoun/GaelO#158]

**Comment by salimkanoun** [comment]
@EmilieOLIVIE je vois pas pourquoi on avait mis que l'investigateur ne pouvait pas delete une visit "Not Done",
j'ai enlevé le check, l'investigateur doit pouvoir delete une visit Not Done (je vois pas de code dans GaelO1 qui l'interdise)

=> Checker que c'est possible dans le front de delete une visit qui est "Not Done"
