### ISSUE TITLE
Instructions for Docker run. 

### ISSUE THREAD

**Issue by Luab** [salimkanoun/GaelO#22]
Hi.
Thx for awesome project. I would like to use it in our lab. 
Can you provide detailed instructions how to run docker version? 
I tried docker build, followed by docker run --publish=80:80, but no sucess. Am I missing some critical steps? Is the port exposed correct?

**Comment by salimkanoun** [comment]
hi @Luab ,

Yes the port is correct, it should run, did you get error message ?
GaelO strongly rely on Orthanc, you have an docker compose script that will install dependencies for you : https://github.com/salimkanoun/GaelO_Installation

You can get additional informations on : https://github.com/salimkanoun/GaelO_Installation/tree/master/README

This project is really recent, i didn't made official anouncement yet and i'm still working to start the first real study that will be using GaelO.

I would be interested to get a call with you, to know what you want to achieve and help you to get things working

**Comment by Luab** [comment]
Sorry for delay.

**Comment by Luab** [comment]
Thanks for the instructions, I'll try to set it up. 
I will gladly discuss our use case. Email me at b.maksduov (at) innopolis.ru, so we could set up a time.

**Comment by salimkanoun** [comment]
Hi, I got an email rejection for your email address.
@Luab  could you write me an email at salim.kanoun@gmail.com

salim

**Comment by salimkanoun** [comment]
No news
