### ISSUE TITLE
Bug sur le use case ModifyUserIdentification

### ISSUE THREAD

**Issue by argetsky** [salimkanoun/GaelO#456]
N'importe quelle modification (sur l'email ou seulement sur first name/last name/phone) semble reset le password mais n'envoie pas d'email pour le redéfinir.

- [x] Pas d'email de vérification envoyé si on change l'email
- [x] Le password est reset pour toute modification, que l'on ait modifié l'email ou simplement un autre champ

Ces problèmes n'apparaissent pas avec le use case ModifyUser (un mail de vérification de l'email est bien envoyé si on change le mail ; le password n'est pas reset si on change une autre information)

**Comment by salimkanoun** [comment]
Je m en occupe ce weekend

**Comment by salimkanoun** [comment]
Good !
