### ISSUE TITLE
Tools routes inutilisées

### ISSUE THREAD

**Issue by argetsky** [salimkanoun/GaelO#670]
`Route::post('tools/centers/patients-from-centers', [ToolsController::class, 'getPatientsInStudyFromCenters']);
    Route::post('tools/patients/visits-from-patients', [ToolsController::class, 'getPatientsVisitsInStudy']);`

Ces deux routes ont l'air de ne jamais être utilisées dans le Front (legacy d'une première version du Workflow manager dans lequel on en avait besoin, il me semble)

**Comment by salimkanoun** [comment]
Ouaip mais on va garder ca peut toujours servir un jour (maintenant qu'elles sont faites..)
