### ISSUE TITLE
Periode refractaire à la reactivation du user apres un delete

### ISSUE THREAD

**Issue by louannecostes** [salimkanoun/GaelO#703]

**Comment by salimkanoun** [comment]
En fait ce n'est pas un bug il y a un trottle dans laravel pour le reset password, par defaut à 60 secondes, configurable via la config

`    'passwords' => [
        'users' => [
            'provider' => 'users',
            'table' => 'password_resets',
            'expire' => 60,
            'throttle' => 60, // Allows a user to request 1 token per 60 seconds
        ],
    ],`
